### ISSUE TITLE
Configuration of plugin in cli.ini

### ISSUE THREAD

**Issue by norbusan** [obynio/certbot-plugin-gandi#16]
Thanks for the great plugin, that is much appreciated!

First of all, all works when run from the command line, there are no issues.

Now I am trying to put the necessary arguments into the `/etc/letsencrypt/cli.ini` which is read by certbot (at least on Debian systems). The content there now looks like
```
# Because we are using logrotate for greater flexibility, disable the
# internal certbot logrotation.
max-log-backups = 0
authenticator = certbot-plugin-gandi:dns
certbot-plugin-gandi:dns-credential = /etc/letsencrypt/gandi.ini
```

Unfortunately, this is not accepted by certbot conf file parser:
```
certbot: error: ambiguous option: --certbot-plugin-gandi could match --certbot-plugin-gandi:dns-propagation-seconds, --certbot-plugin-gandi:dns-credentials
```
it seems to break at the colon.

Do you know a way around this? Other plugins don't use the colon notation.

Thanks

Norbert

**Comment by norbusan** [comment]
Oohh, aah, sorry for the noise: It is impossible https://github.com/certbot/certbot/issues/7681

**Comment by obynio** [comment]
Yeah, no choice here. People can put their configuration in `/etc/letsencrypt/gandi.ini` like you did.

**Comment by 7auser** [comment]
Your Plugin is very usefull and also pretty easy to work with. Thanks a lot!
I ran into a problem trying out renewing. The error is get is this:
Attempting to renew cert (mydomain.com) from /etc/letsencrypt/renewal/mydomain.com.conf produced an unexpected error: Missing command line flag or config entry for this setting:
Input the path to your Gandi credentials INI file. Skipping.
Is this due to this problem? If so what would be the workaround?
here is the option part of my renewal conf:
# Options used in the renewal process
[renewalparams]
account = XYZ
server = https://acme-v02.api.letsencrypt.org/directory
authenticator = certbot-plugin-gandi:dns
certbot-plugin-gandi:dns-credential = /etc/letsencrypt/gandi.ini

Any help is appreciated!

**Comment by obynio** [comment]
@7auser  The plugin configuration must be provided by CLI, configuration for third-party plugins in `cli.ini` is not supported by certbot for the moment. Please refer to the following issues for details.

https://github.com/certbot/certbot/issues/4351
https://github.com/certbot/certbot/issues/6504 
https://github.com/certbot/certbot/issues/7681
