### ISSUE TITLE
Property "certbot_plugin_gandi:dns_api_key" not found

### ISSUE THREAD

**Issue by ema** [obynio/certbot-plugin-gandi#26]
Setting `dns_gandi_api_key=APIKEY` in `gandi.ini` as mentioned in [the docs](https://github.com/obynio/certbot-plugin-gandi/blob/master/README.md), I get the following error:

```
Attempting to renew cert (example.org) from /etc/letsencrypt/renewal/example.org.conf produced an unexpected error: Missing property in credentials configuration file /etc/letsencrypt/gandi.ini:
 * Property "certbot_plugin_gandi:dns_api_key" not found (should be API key for Gandi account).. Skipping.
```
The correct property seems to be `certbot_plugin_gandi:dns_api_key` instead.

Thanks for this plugin!

**Comment by obynio** [comment]
Hey hello @ema. You're most likely mixing prefix-based cli arguments with non-prefix-based ini configuration. Certbot deprecated 3rd party plugins prefixes so I had to update the configuration format a few days ago. 

A warning was added since 1.3.0 (see #24). I do not have control over the debian release which is still using 1.2.5 so the change was not propagated. If you keep using prefix-based cli arguments, stay consistent and use prefix-based configuration in the ini file.

But I agree the documentation is somewhat confusing, so I added some details in the FAQ of the plugin.

See https://github.com/certbot/certbot/pull/8131 and https://github.com/obynio/certbot-plugin-gandi/issues/23 for details.
